import React, { useEffect, useState } from 'react';
import { AlertTriangle, BookOpen, ClipboardCheck, GraduationCap, Users } from 'lucide-react';
import { reportService } from '../services/reportService';
import LoadingSpinner from '../components/LoadingSpinner';

const HodDashboard = () => {
  const [state, setState] = useState(null);
  useEffect(() => { Promise.all([reportService.getDashboardStats(), reportService.getReports()]).then(([stats, reports]) => setState({ stats: stats.data, sessions: stats.data?.recentSessions || [], reports: reports.data })).catch(() => setState({ error: true })); }, []);
  if (!state) return <div className="min-h-[50vh] flex items-center justify-center"><LoadingSpinner text="Loading department data..." /></div>;
  if (state.error) return <p className="text-rose-400">Unable to load department data.</p>;
  const { stats } = state;
  const cards = [{ label: 'Students', value: stats.totalStudents, icon: GraduationCap }, { label: 'Faculty', value: stats.totalFaculty, icon: Users }, { label: 'Classes', value: stats.totalClasses, icon: BookOpen }, { label: 'Attendance', value: `${stats.attendancePercentage}%`, icon: ClipboardCheck }];
  return <div className="dashboard-page"><header className="dashboard-header"><div><p className="eyebrow">Department overview</p><h1>Attendance at a glance</h1><p className="header-subtitle">Department-scoped performance and recent sessions.</p></div></header><section className="dashboard-stats">{cards.map(({ label, value, icon: Icon }) => <article className="dashboard-stat stat-blue" key={label}><div><p>{label}</p><strong>{value}</strong><span>Assigned department scope</span></div><Icon /></article>)}</section><section className="attendance-overview-grid"><div className="dashboard-section dashboard-panel"><div className="section-heading"><div><h2>Attendance health</h2><p>Current recorded attendance</p></div></div><div className="overview-list"><div><span>Present today</span><strong className="text-emerald-400">{stats.todayPresent}</strong></div><div><span>Absent today</span><strong className="text-rose-400">{stats.todayAbsent}</strong></div><div><span>Late today</span><strong className="text-amber-400">{stats.todayLate}</strong></div></div></div><div className="dashboard-section dashboard-panel"><div className="section-heading"><div><h2>Attention needed</h2><p>Configured threshold: {stats.attendanceThreshold}%</p></div><AlertTriangle /></div><div className="overview-list"><div><span>Pending corrections</span><strong>{stats.pendingCorrectionRequests}</strong></div><div><span>Below threshold</span><strong>{stats.lowAttendanceStudents}</strong></div></div></div></section><section className="dashboard-section sessions-section dashboard-panel"><div className="section-heading"><div><h2>Recent department sessions</h2><p>Attendance sessions visible in your departments</p></div></div><div className="table-scroll"><table className="dashboard-table"><thead><tr><th>Class</th><th>Subject</th><th>Teacher</th><th>Status</th></tr></thead><tbody>{state.sessions.length ? state.sessions.slice(0, 8).map(session => <tr key={session._id}><td>{session.classId?.name} ({session.classId?.section})</td><td>{session.subject}</td><td>{session.startedBy?.fullName || 'Unknown'}</td><td>{session.status}</td></tr>) : <tr><td colSpan="4" className="empty-row">No department sessions recorded yet.</td></tr>}</tbody></table></div></section></div>;
};

export default HodDashboard;